### ISSUE TITLE
converting matlab to python

### ISSUE THREAD

**Issue by semi-kim** [yyhz76/reflectSuppress#1]
hi
im converting your matlab code to python
can i ask something?
1. why you used matlab not python?

2. and i dont know why in my python code cant execute
and no error

**Comment by yyhz76** [comment]
Here is the comparison between the matlab implementation and your Python implementation:

Matlab implementation:         Ar(:, 1:n-1)  =A(:, 2:n);
Your Python implementation: Ar[:, 0:n-2]=A[:, 1:n-1]


Note that in Matlab  1:n-1 expands to [1, 2, ..., n - 1],    **n - 1 numbers in total**
while in Python 0:n-2 expands to [0, 1, ... n-3].               **n - 2 numbers in total**

This is where things might go wrong.

Need to make similar changes accordingly throughout your Python implementation
